Repository microsoft/generative-ai-for-beginners, pull requests merged in 2023-11, with the labels that each got.

#91 fix lesson 11 broken link
  README.md
Labels: documentation

#139 Create validate-markdown.yml
  .github/workflows/validate-markdown.yml
Labels: needs-review

#145 fix: checkout to correct repo
  .github/workflows/validate-markdown.yml
Labels: needs-review

#146 fix: links issues 2
  00-course-setup/README.md
  01-introduction-to-genai/README.md
  02-exploring-and-comparing-different-llms/README.md
  03-using-generative-ai-responsibly/README.md
  04-prompt-engineering-fundamentals/1-introduction.ipynb
  04-prompt-engineering-fundamentals/README.md
  05-advanced-prompts/README.md
  06-text-generation-apps/README.md
  06-text-generation-apps/notebook-azure-openai.ipynb
  07-building-chat-applications/README.md
  07-building-chat-applications/notebook-azure-openai.ipynb
  07-building-chat-applications/notebook-openai.ipynb
  08-building-search-applications/README.md
  08-building-search-applications/scripts/README.md
  09-building-image-applications/README.md
  09-building-image-applications/notebook-azureopenai.ipynb
  10-building-low-code-ai-applications/README.md
  11-integrating-with-function-calling/README.md
  12-designing-ux-for-ai-applications/README.md
  13-continued-learning/README.md
  README.md
Labels: needs-review

#148 fixed Chinese content
  00-course-setup/translations/cn/README.md
  01-introduction-to-genai/translations/cn/README.md
  02-exploring-and-comparing-different-llms/translations/cn/README.md
  03-using-generative-ai-responsibly/translations/cn/README.md
  04-prompt-engineering-fundamentals/translations/cn/README.md
  05-advanced-prompts/translations/cn/README.md
  06-text-generation-apps/translations/cn/README.md
  07-building-chat-applications/translations/cn/README.md
  08-building-search-applications/translations/cn/README.md
  09-building-image-applications/translations/cn/README.md
  10-building-low-code-ai-applications/translations/cn/README.md
  11-integrating-with-function-calling/transaltions/cn/README.md
  12-designing-ux-for-ai-applications/translations/cn/README.md
  13-continued-learning/translations/cn/README.md
  translation/cn/README.md
Labels: needs-review

#152 Improve workflow
  .github/workflows/validate-markdown.yml
Labels: needs-review

#154 Improve workflow
  .github/markdown_checker.py
  00-course-setup/translations/cn/README.md
  translation/cn/README.md
Labels: needs-review

#156 Tidying files and folders
  01-introduction-to-genai/images/genai_course_1[83].png
  02-exploring-and-comparing-different-llms/images/README.md
  03-using-generative-ai-responsibly/README.md
  03-using-generative-ai-responsibly/images/03-lesson-banner.png
  03-using-generative-ai-responsibly/images/ChatGPT-titanic-survivor-prompt.webp
  03-using-generative-ai-responsibly/translations/cn/README.md
  04-prompt-engineering-fundamentals/README.md
  04-prompt-engineering-fundamentals/images/04-hallucination-aoai.png
  04-prompt-engineering-fundamentals/images/04-hallucination-huggingchat.png
  04-prompt-engineering-fundamentals/images/04-hallucination-oai.png
  04-prompt-engineering-fundamentals/images/04-lesson-banner.png
  04-prompt-engineering-fundamentals/images/04-playground-chat-base.png
  04-prompt-engineering-fundamentals/images/04-playground-chat-instructions.png
  04-prompt-engineering-fundamentals/images/04-tokenizer-example.png
  04-prompt-engineering-fundamentals/translations/cn/README.md
  05-advanced-prompts/translations/cn/README.md
  07-building-chat-applications/README.md
  07-building-chat-applications/images/07-lesson-banner.png
  07-building-chat-applications/images/custom-instructions.png
  07-building-chat-applications/images/lesson-plan-prompt.png
  07-building-chat-applications/translations/cn/README.md
  08-building-search-applications/README.md
  08-building-search-applications/images/08-lesson-banner.png
  08-building-search-applications/images/notebook-search.png
  08-building-search-applications/images/query-results.png
  08-building-search-applications/translations/cn/README.md
  09-building-image-applications/README.md
  09-building-image-applications/app-variation.py
  09-building-image-applications/app.py
  09-building-image-applications/generated-image.png
  09-building-image-applications/images/09-lesson-banner.png
  09-building-image-applications/images/generated-image.png
  09-building-image-applications/images/v1-generated-image.png
  09-building-image-applications/images/v1-low-temp-generated-image.png
  09-building-image-applications/images/v1-temp-generated-image.png
  09-building-image-applications/images/v2-generated-image.png
  09-building-image-applications/images/v2-low-temp-generated-image.png
  09-building-image-applications/images/v2-temp-generated-image.png
  09-building-image-applications/notebook-azureopenai.ipynb
  09-building-image-applications/translations/cn/README.md
  11-integrating-with-function-calling/README.md
  11-integrating-with-function-calling/images/11-lesson-banner.png
  11-integrating-with-function-calling/transaltions/cn/README.md
  12-designing-ux-for-ai-applications/README.md
  img/android-chrome-192x192.png
  img/android-chrome-512x512.png
  img/apple-touch-icon.png
  img/favicon-16x16.png
  img/favicon-32x32.png
  img/favicon.ico
  img/site.webmanifest
  index.html
Labels: needs-review

#157 fix: workflow skips execution
  .github/workflows/validate-markdown.yml
Labels: needs-review

#161 Contributing guidance
  CONTRIBUTING.md
  README.md
  images/android-chrome-192x192.png
  images/android-chrome-512x512.png
  images/apple-touch-icon.png
  images/favicon-16x16.png
  images/favicon-32x32.png
  images/favicon.ico
  images/github-check-country-locale-comment.png
  images/github-check-paths-missing-tracking-comment.png
  images/github-check-urls-missing-tracking-comment.png
  images/logo.png
  images/repository-thumbnail.png
  images/site.webmanifest
  images/vscode-follow-link.png
  images/vscode-select-relative-path.png
  index.html
  translation/cn/README.md
Labels: question, needs-review

#162 Contributing guidance
  09-building-image-applications/translations/cn/README.md
  CONTRIBUTING.md
Labels: needs-review

#164 Updated "hallucination" to "fabrication" for responsible usage
  04-prompt-engineering-fundamentals/README.md
  04-prompt-engineering-fundamentals/images/04-fabrication-aoai.png
  04-prompt-engineering-fundamentals/images/04-fabrication-huggingchat.png
  04-prompt-engineering-fundamentals/images/04-fabrication-oai.png
Labels: needs-review

#149 Fix typos on prompt engineering fundamentals chapter
  04-prompt-engineering-fundamentals/README.md
Labels: needs-review

#165 Updated CN Translation - to reflect changed filenames
  04-prompt-engineering-fundamentals/README.md
  04-prompt-engineering-fundamentals/translations/cn/README.md
Labels: needs-review

#166 Replaced 'hallucination' references in other lessons (and notebook)
  01-introduction-to-genai/README.md
  02-exploring-and-comparing-different-llms/README.md
  04-prompt-engineering-fundamentals/1-introduction.ipynb
  04-prompt-engineering-fundamentals/translations/cn/README.md
Labels: needs-review

#163 DevContainer Setup fix
  .devcontainer/Setup.txt
  .devcontainer/devcontainer.json
  .devcontainer/requirements.txt
Labels: needs-review

#169 Fixed Missing Notebook links
  07-building-chat-applications/README.md
  07-building-chat-applications/translations/cn/README.md
Labels: needs-review

#172 Update README.md
  06-text-generation-apps/README.md
Labels: needs-review

#173 Update README.md
  06-text-generation-apps/README.md
Labels: needs-review

#175 using the "your" voice in the readme file
  README.md
Labels: needs-review

#178 Fixed VSCode hyperlink
  00-course-setup/README.md
Labels: needs-review

#179 Chore/fix openai update
  04-prompt-engineering-fundamentals/1-introduction.ipynb
Labels: needs-review

#171 Add line breaks to improve image alignment in README
  01-introduction-to-genai/README.md
Labels: needs-review

#183 use meta_prompt in the example prompt
  09-building-image-applications/README.md
  09-building-image-applications/translations/cn/README.md
Labels: needs-review

#186 correct typo in chain-of-thought
  05-advanced-prompts/README.md
Labels: needs-review

#192 Fix security issue
  .github/markdown_checker.py
  .github/workflows/validate-markdown.yml
Labels: needs-review

#193 feat: language selection
  docs/_navbar.md
  index.html
Labels: needs-review

#195 Add references to resources section
  13-continued-learning/README.md
Labels: needs-review

#194 Fix link for OpenAI signup
  00-course-setup/README.md
Labels: needs-review

#196 Create .nojekyll
  docs/.nojekyll
Labels: needs-review

#197 fix/navbar - fixes issue where navbar is not seen in hosted GitHub Pages
  .nojekyll
Labels: needs-review

#202 adding dotnet lessons, also adding simpler notebooks for ch07 and ch0…
  06-text-generation-apps/app-recipe.py
  07-building-chat-applications/dotnet/notebook-azure-openai.dib
  07-building-chat-applications/notebook-simple-azure-openai.ipynb
  08-building-search-applications/dotnet/notebook-azure-openai.dib
  08-building-search-applications/notebook-azure-openai-simple.ipynb
  09-building-image-applications/app.py
  09-building-image-applications/dotnet/notebook-azure-openai.dib
  09-building-image-applications/images/generated-image.png
Labels: needs-review

#207 Fixing a typo
  08-building-search-applications/README.md
Labels: needs-review

#205 Properly uppercase GitHub
  .devcontainer/devcontainer.json
  .github/workflows/deploy-quiz-app.yml
  00-course-setup/README.md
  00-course-setup/translations/cn/README.md
Labels: needs-review

#206 Add link to MSOS Code of Conduct
  00-course-setup/README.md
Labels: needs-review
