Repository microsoft/generative-ai-for-beginners, pull requests merged in 2024-02, with the labels that each got.

#286 feat: Lesson 9 - Building Image Generation Applications - TypeScript sample
  09-building-image-applications/typescript/image-generation-app/.env-sample
  09-building-image-applications/typescript/image-generation-app/package-lock.json
  09-building-image-applications/typescript/image-generation-app/package.json
  09-building-image-applications/typescript/image-generation-app/src/main.ts
  09-building-image-applications/typescript/image-generation-app/tsconfig.json
Labels: needs-review, V2

#277 feat: Lesson 6 - Building Text Generation Applications - TypeScript Sample
  06-text-generation-apps/typescript/.gitignore
  06-text-generation-apps/typescript/recipe-app/.env-sample
  06-text-generation-apps/typescript/recipe-app/package-lock.json
  06-text-generation-apps/typescript/recipe-app/package.json
  06-text-generation-apps/typescript/recipe-app/src/main.ts
  06-text-generation-apps/typescript/recipe-app/tsconfig.json
Labels: needs-review, V2

#280 feat: Lesson 8 - Building a Search Applications - TypeScript sample
  08-building-search-applications/typescript/.gitignore
  08-building-search-applications/typescript/search-app/.env-sample
  08-building-search-applications/typescript/search-app/package-lock.json
  08-building-search-applications/typescript/search-app/package.json
  08-building-search-applications/typescript/search-app/src/main.ts
  08-building-search-applications/typescript/search-app/tsconfig.json
Labels: needs-review, V2

#278 feat: Lesson 7 - Building Chat Applications - TypeScript Sample
  07-building-chat-applications/typescript/.gitignore
  07-building-chat-applications/typescript/chat-completions-app/.env-sample
  07-building-chat-applications/typescript/chat-completions-app/package-lock.json
  07-building-chat-applications/typescript/chat-completions-app/package.json
  07-building-chat-applications/typescript/chat-completions-app/src/main.ts
  07-building-chat-applications/typescript/chat-completions-app/tsconfig.json
Labels: needs-review, V2

#296 Moved env setup to separate file for potential reuse.
  04-prompt-engineering-fundamentals/1-introduction.ipynb
  04-prompt-engineering-fundamentals/README.md
  04-prompt-engineering-fundamentals/SETUP.md
Labels: needs-review

#298 Adding support to non-Azure OpenAI endpoints to chapter 7
  .env.copy
  07-building-chat-applications/README.md
  07-building-chat-applications/python/aoai-assigment-simple.ipynb
  07-building-chat-applications/python/aoai-assignment.ipynb
  07-building-chat-applications/python/oai-assigment-simple.ipynb
  07-building-chat-applications/python/oai-assignment.ipynb
  07-building-chat-applications/translations/cn/README.md
  07-building-chat-applications/translations/ja-jp/README.md
  07-building-chat-applications/translations/pt-br/README.md
Labels: V2

#303 Update README.md
  README.md
Labels: needs-review

#304 Added new video links and 2 new lessons
  01-introduction-to-genai/translations/cn/README.md
  01-introduction-to-genai/translations/es-mx/README.md
  01-introduction-to-genai/translations/ja-jp/README.md
  01-introduction-to-genai/translations/pt-br/README.md
  02-exploring-and-comparing-different-llms/translations/cn/README.md
  02-exploring-and-comparing-different-llms/translations/ja-jp/README.md
  02-exploring-and-comparing-different-llms/translations/pt-br/README.md
  04-prompt-engineering-fundamentals/README.md
  04-prompt-engineering-fundamentals/translations/cn/README.md
  04-prompt-engineering-fundamentals/translations/ja-jp/README.md
  04-prompt-engineering-fundamentals/translations/pt-br/README.md
  05-advanced-prompts/README.md
  05-advanced-prompts/translations/cn/README.md
  05-advanced-prompts/translations/ja-jp/README.md
  05-advanced-prompts/translations/pt-br/README.md
  06-text-generation-apps/README.md
  06-text-generation-apps/translations/cn/README.md
  06-text-generation-apps/translations/ja-jp/README.md
  06-text-generation-apps/translations/pt-br/README.md
  07-building-chat-applications/README.md
  07-building-chat-applications/translations/cn/README.md
  07-building-chat-applications/translations/ja-jp/README.md
  07-building-chat-applications/translations/pt-br/README.md
  10-building-low-code-ai-applications/README.md
  10-building-low-code-ai-applications/translations/cn/README.md
  10-building-low-code-ai-applications/translations/ja-jp/README.md
  10-building-low-code-ai-applications/translations/pt-br/README.md
  12-designing-ux-for-ai-applications/README.md
  12-designing-ux-for-ai-applications/translations/cn/README.md
  12-designing-ux-for-ai-applications/translations/ja-jp/README.md
  12-designing-ux-for-ai-applications/translations/pt-br/README.md
  13-securing-ai-applications/README.md
  13-securing-ai-applications/images/13-AI-red-team.png
  13-securing-ai-applications/images/13-lesson-banner.jpg
  17-ai-agents/README.md
  README.md
Labels: needs-review

#306 added open source lesson
  16-open-source-models/README.MD
  16-open-source-models/images/choose-model.png
  16-open-source-models/images/model-price.png
  16-open-source-models/images/model-quality.png
  README.md
Labels: needs-review

#308 fixed lesson 16 link
  README.md
Labels: needs-review
